export type GmshOp = 'add' | 'cut' | 'intersect';
export type GmshPrimitiveKind = 'line' | 'rectangle' | 'disk' | 'polygon';

export type GmshPart = {
  id: string;
  name: string;
  visible: boolean;
  locked: boolean;
  color: string;
};

export type GmshPrimitive =
  | {
      id: string;
      partId: string;
      active: boolean;
      kind: 'line';
      op: GmshOp;
      x1: number;
      y1: number;
      x2: number;
      y2: number;
      construction?: boolean;
    }
  | {
      id: string;
      partId: string;
      active: boolean;
      kind: 'rectangle';
      op: GmshOp;
      x: number;
      y: number;
      w: number;
      h: number;
    }
  | {
      id: string;
      partId: string;
      active: boolean;
      kind: 'disk';
      op: GmshOp;
      cx: number;
      cy: number;
      r: number;
    }
  | {
      id: string;
      partId: string;
      active: boolean;
      kind: 'polygon';
      op: GmshOp;
      points: Array<{ x: number; y: number }>;
    };

export type GmshExtrude = {
  id: string;
  sourcePrimitiveId: string;
  active: boolean;
  dz: number;
  layers: number;
  recombine: boolean;
};

export type GmshPolygonConstraintKind = 'horizontal' | 'vertical' | 'equal_edge' | 'parallel' | 'perpendicular';

export type GmshPolygonConstraint = {
  id: string;
  primitiveId: string;
  kind: GmshPolygonConstraintKind;
  edgeA: number;
  edgeB?: number;
};

export type GmshPolygonDimension = {
  id: string;
  primitiveId: string;
  edge: number;
  length: number;
};

export type GmshModel = {
  name: string;
  lc: number;
  parts: GmshPart[];
  primitives: GmshPrimitive[];
  extrusions: GmshExtrude[];
  polygonConstraints: GmshPolygonConstraint[];
  polygonDimensions: GmshPolygonDimension[];
};

export function createDefaultGmshModel(): GmshModel {
  return {
    name: 'gmsh_model',
    lc: 1,
    parts: [{ id: 'PART-1', name: 'Part 1', visible: true, locked: false, color: '#4ade80' }],
    primitives: [
      { id: 'P-1', partId: 'PART-1', active: true, kind: 'rectangle', op: 'add', x: -40, y: -20, w: 80, h: 40 },
      { id: 'P-2', partId: 'PART-1', active: true, kind: 'disk', op: 'cut', cx: 0, cy: 0, r: 8 }
    ],
    extrusions: [{ id: 'E-1', sourcePrimitiveId: 'P-1', active: true, dz: 6, layers: 3, recombine: true }],
    polygonConstraints: [],
    polygonDimensions: []
  };
}

export function nextId(prefix: string, existingIds: string[]): string {
  let i = 1;
  while (existingIds.includes(`${prefix}-${i}`)) i += 1;
  return `${prefix}-${i}`;
}

export function generateGeo(model: GmshModel): string {
  let surfaceTag = 1;
  let pointTag = 1;
  let curveTag = 1;
  const primitiveToSurface = new Map<string, number>();
  const addTags: number[] = [];
  const cutTags: number[] = [];
  const intersectTags: number[] = [];

  const lines: string[] = [];
  lines.push('// Generated by Structural Companion Gmsh Modeler');
  lines.push(`// model: ${model.name}`);
  lines.push('SetFactory("OpenCASCADE");');
  lines.push(`Mesh.CharacteristicLengthMax = ${model.lc};`);
  lines.push('');

  for (const p of model.primitives.filter((x) => x.active)) {
    if (p.kind === 'line') {
      const p1 = pointTag++;
      const p2 = pointTag++;
      const l1 = curveTag++;
      lines.push(`Point(${p1}) = {${p.x1}, ${p.y1}, 0, ${model.lc}};`);
      lines.push(`Point(${p2}) = {${p.x2}, ${p.y2}, 0, ${model.lc}};`);
      lines.push(`Line(${l1}) = {${p1}, ${p2}};`);
      continue;
    }
    const sTag = surfaceTag++;
    primitiveToSurface.set(p.id, sTag);
    if (p.kind === 'rectangle') {
      lines.push(`Rectangle(${sTag}) = {${p.x}, ${p.y}, 0, ${p.w}, ${p.h}};`);
    } else if (p.kind === 'disk') {
      lines.push(`Disk(${sTag}) = {${p.cx}, ${p.cy}, 0, ${p.r}, ${p.r}};`);
    } else {
      if (p.points.length < 3) continue;
      const pTags: number[] = [];
      for (const pt of p.points) {
        const pTag = pointTag++;
        pTags.push(pTag);
        lines.push(`Point(${pTag}) = {${pt.x}, ${pt.y}, 0, ${model.lc}};`);
      }
      const lTags: number[] = [];
      for (let i = 0; i < pTags.length; i += 1) {
        const a = pTags[i];
        const b = pTags[(i + 1) % pTags.length];
        const lTag = curveTag++;
        lTags.push(lTag);
        lines.push(`Line(${lTag}) = {${a}, ${b}};`);
      }
      const loopTag = curveTag++;
      lines.push(`Curve Loop(${loopTag}) = {${lTags.join(', ')}};`);
      lines.push(`Plane Surface(${sTag}) = {${loopTag}};`);
    }
    if (p.op === 'add') addTags.push(sTag);
    else if (p.op === 'cut') cutTags.push(sTag);
    else intersectTags.push(sTag);
  }

  lines.push('');
  if (!addTags.length) {
    lines.push('// No additive primitives were found. Add at least one base primitive.');
    lines.push('Coherence;');
    lines.push('Mesh 2;');
    return lines.join('\n');
  }

  let baseSurface = addTags[0];
  if (addTags.length > 1) {
    lines.push(`BooleanUnion{ Surface{${addTags.join(', ')}}; Delete; }{ }`);
    lines.push(`base[] = Surface In BoundingBox{-1e9,-1e9,-1e9,1e9,1e9,1e9};`);
    lines.push('If (#base[] > 0)');
    lines.push('  sbase = base[0];');
    lines.push('EndIf');
  } else {
    lines.push(`sbase = ${baseSurface};`);
  }

  if (intersectTags.length) {
    lines.push(`BooleanIntersection{ Surface{sbase}; Delete; }{ Surface{${intersectTags.join(', ')}}; Delete; }`);
    lines.push(`inter[] = Surface In BoundingBox{-1e9,-1e9,-1e9,1e9,1e9,1e9};`);
    lines.push('If (#inter[] > 0)');
    lines.push('  sbase = inter[0];');
    lines.push('EndIf');
  }

  if (cutTags.length) {
    lines.push(`BooleanDifference{ Surface{sbase}; Delete; }{ Surface{${cutTags.join(', ')}}; Delete; }`);
    lines.push(`diff[] = Surface In BoundingBox{-1e9,-1e9,-1e9,1e9,1e9,1e9};`);
    lines.push('If (#diff[] > 0)');
    lines.push('  sbase = diff[0];');
    lines.push('EndIf');
  }

  lines.push('');
  for (const ex of model.extrusions.filter((x) => x.active)) {
    const layers = Math.max(1, Math.floor(ex.layers));
    const dz = ex.dz;
    lines.push(`// ${ex.id} from ${ex.sourcePrimitiveId}`);
    lines.push(`ex_${ex.id.replace(/[^A-Za-z0-9_]/g, '_')}[] = Extrude {0, 0, ${dz}} {`);
    lines.push('  Surface{sbase};');
    lines.push(`  Layers{${layers}};`);
    if (ex.recombine) lines.push('  Recombine;');
    lines.push('};');
  }

  lines.push('');
  lines.push('Coherence;');
  lines.push('Mesh 3;');
  return lines.join('\n');
}
